### ISSUE TITLE
Fix "Your first application" documentation page

### ISSUE THREAD

**Issue by mcornaton** [iExecBlockchainComputing/documentation-old#68]
In "Your first application" documentation page, a few text should be fixed:

- section "Application input files" > "Input files (public):", a sentence seems to be incomplete: "The total number of input files is stored in the variable.". The variable name `IEXEC_INPUT_FILES_NUMBER` is probably missing.
- section "Test your app on iExec" > "Push your app to Dockerhub", the sentence "Congratulation, you app is ready to be deployed on iExec!" should be fixed to "Congratulation**s**, you**r** app is ready to be deployed on iExec!".
- section "Test your app on iExec" > "Run your app on iExec", the last sentence misses a "s" at "Congratulation**s**".
- section "Publish your app on the iExec marketplace", the only sentence misses a "s" at "Congratulation**s**".

**Comment by PierreJeanjacquot** [comment]
Great, feel free to submit a PR on the default branch `v6-staging` to fix it!
(Pushing your branch in this repo will automatically create the rendered version on https://documentations.iex.ec/staging/v/your-branch-name/)
Once merged, your changes will be reflected on https://documentations.iex.ec/staging/
Eventually, `v6-staging` will be merged into `v6-prod` to ship to production (https://docs.iex.ec).

**Comment by PierreJeanjacquot** [comment]
will be merged in https://github.com/iExecBlockchainComputing/documentation/pull/70
