### ISSUE TITLE
Mail link does not render properly

### ISSUE THREAD

**Issue by mcornaton** [iExecBlockchainComputing/documentation-old#74]
In _documentation/for-developers/confidential-computing/create-your-first-sgx-app.md_, the new mail link does not render properly:
![image](https://user-images.githubusercontent.com/87655102/126609545-02e73075-61de-4be2-973c-e8a296ca918f.png)

**Comment by PierreJeanjacquot** [comment]
@mcornaton I did some fix on encoding earlier, do you still experience this issue?

**Comment by mcornaton** [comment]
No, that's now working. I close the issue. Thanks!
